### PR TITLE
Add optional support for serialization

### PR DESCRIPTION
**Pull request by spersson**
Adds a non-default feature for serializing stashes with serde.

One of the advantages of building a graph on top of stash instead of using pointers is the possibility to serialize the graph!

### CODE REVIEW

**Comment by Stebalien** [comment]
Unfortunately, this includes a lot of runtime state (the free list and empty stash entries). I'd prefer to serialize the Stash to a map `{usize: value}` and the unique stash to a sequence `[{version: N, value: V}, {version: M}]` (where the entry with version `M` is empty and therefore has no value (is skipped)).

Think you could write custom (de)serialize implementations?

**Comment by spersson** [comment]
On 2018-07-30 01:13, Steven Allen wrote:

> Unfortunately, this includes a lot of runtime state (the free list and empty stash entries). I'd prefer to serialize the Stash to a map {usize: value} and the unique stash to a sequence [{version: N, value: V}, {version: M}] (where the entry with version M is empty and therefore has no value (is skipped)). 
> 
> Think you could write custom (de)serialize implementations? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

For Stash you mean a map from index types to values, right? And the
point would be to reduce memory use of the serialized version? 

Am I right in thinking that it might not always be a space saving?
What I'm thinking is that of course it would depend on how full your
stash is. And also on details of the serialization format. But I believe
many formats store a vector as just a length followed by all the values.
Meaning indices are not stored for each item, compared to your
suggestion which does.
I think that before spending time on a custom serialization I would want
to benchmark sizes for realistic scenarios to understand the tradeoffs.
Unfortunately my interest in stash is mostly for my prototype hobby
programming language, which does not even have any removal operations
yet so stashes are always full. Not very realistic. 

 

Links:
------
[1] https://github.com/Stebalien/stash-rs/pull/8#issuecomment-408691739
[2]

**Comment by Stebalien** [comment]
> What I'm thinking is that of course it would depend on how full your stash is.

It should be smaller in (almost) all cases. We'd be adding the indices but removing the free list (same sizes as the indices), the empty/full enums (probably a couple of bytes per item), and the empty slots.

**Comment by spersson** [comment]
I did some testing. Adding the following code:
```rust
#[cfg(feature = "serialization")]
mod serialization {
    use super::*;
    use serde::{de, Deserialize, Deserializer, Serialize, Serializer};
    use std::collections::HashMap;

    impl<V, Ix> Serialize for Stash<V, Ix> where V: Serialize+Clone, Ix: Index {
        fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
            let mut map = HashMap::new();
            for (i, v) in self {
                map.insert(i.into_usize(), v.clone());
            }
            map.serialize(serializer)
        }
    }
}
```
Then I wrote a test where I insert 20000 items in a stash and then remove some number of items before sending the stash to bincode to serialize. 
Comparing the output sizes betweeen this method and a simple #[derive(Serialize)] I can see that regardless of size of the stored values, around 75% full is where the two methods produce same size output. If less full then the map method gives smaller output, if fuller than 75% then simple derive gives smaller output.

**Comment by Stebalien** [comment]
Odd. Can I play around with that test? Also, what serialization format did you use?

**Comment by spersson** [comment]
I just updated my branch with the test example I used. By switching checkout between the two last commits you can test the two serialization strategies.

**Comment by Stebalien** [comment]
I see. My reasoning was incorrect. The overhead of the array version is:

* u32 + u64 = 12 bytes per empty item.
* u32 = 4 bytes per full item.

The map version has:

* u64 = 8 bytes per full item.

The cutoff is .75 because: .75 * 8 (map) = .75 * 4 + .25 * 12 (array) = 6

---

On the other hand, CBOR appears to consistently prefer the map version (and seems to be quite a bit more efficient in general). This is probably because it uses varints.

---

I'd still rather not encode the freelist as it's runtime state. How about a sparse array? That is: `[Some(value), Some(value), None, None, Some(value)]`. This appears to be more efficient in in all cases (except a *really* sparse array).

Note: I'm trying to think carefully about this because I don't want to change the format later on (and break existing applications).

```rust
#[cfg(feature = "serialization")]
mod serialization {
    use super::*;
    use serde::{de, ser::SerializeSeq, Deserialize, Deserializer, Serialize, Serializer};
    use std::collections::HashMap;

    impl<V, Ix> Serialize for Stash<V, Ix>
    where
        V: Serialize + Clone,
        Ix: Index,
    {
        fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
            // Find the last non-empty item (may be overkill).
            let count = self
                .data
                .iter()
                .enumerate()
                .rev()
                .find(|(_, v)| match v {
                    Entry::Full(_) => true,
                    Entry::Empty(_) => false,
                }).map(|(i, _)| i + 1)
                .unwrap_or(0);

            // Serialize up to the last non-empty item.
            let mut seq = serializer.serialize_seq(Some(count))?;
            for e in self.data.iter().take(count) {
                seq.serialize_element(&match e {
                    Entry::Full(v) => Some(v),
                    Entry::Empty(_) => None,
                });
            }
            seq.end()
        }
    }
}
```

**Comment by Stebalien** [comment]
By the way, thanks for bearing with me on this.

**Comment by spersson** [comment]
Oh, no worries. You are clearly a good software maintainer, better than I would be.
Your implementation gave me the idea to do run length encoding for even more space saving. 
What do you think?

```rust
 fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
            let mut run_lengths = Vec::new();
            let mut checking_empties = true;
            let mut current_length = 0usize;
            for entry in &self.data {
                match entry {
                    Entry::Empty(_) => {
                        if checking_empties {
                            current_length += 1;
                        } else {
                            run_lengths.push(current_length);
                            current_length = 1;
                            checking_empties = true;
                        }
                    }
                    Entry::Full(_) => {
                        if !checking_empties {
                            current_length += 1;
                        } else {
                            run_lengths.push(current_length);
                            current_length = 1;
                            checking_empties = false;
                        }
                    }
                }
            }
            if !checking_empties {
                run_lengths.push(current_length);
            }

            let mut seq = serializer.serialize_seq(Some(1 + run_lengths.len() + self.len()))?;
            seq.serialize_element(&run_lengths.len());
            for length in &run_lengths {
                seq.serialize_element(length);
            }
            for value in self.values() {
                seq.serialize_element(value);
            }
            seq.end()
        }
```

**Comment by Stebalien** [comment]
It'll probably be more efficient, but I think that goes a bit *too* far. I'd like to be able to, e.g., be able to serialize to JSON or CBOR and then easily read the results in either python or javascript. Both the map and array variants allow for that.

Most decent compression algorithms will handle run-length encoding for us anyways.

**Comment by spersson** [comment]
Yeah, I see that point. I added a simple implementation of your sparse array, both for stash and uniquestash. I didn't think there's a need to store version for empty entries. I also realized I need to add trait implementations for Tag. Please check it out, ready for merging from my perspective. Only testing I have done is to run the tests that I added, you may want to test other formats perhaps.

**Comment by Stebalien** [comment]
> I didn't think there's a need to store version for empty entries.

Unfortunately... there is. If we don't, we can end up reusing old versions. I may still have old tags for empty slots lying around.

> I also realized I need to add trait implementations for Tag.

SGTM.

---

Other than that, the code looks good. Thanks!

**Comment by spersson** [comment]
> > I didn't think there's a need to store version for empty entries.
> Unfortunately... there is. If we don't, we can end up reusing old versions.

Just to explain my thinking:
I was thinking that the deserialized uniquestash should be considered like a new one where you have just inserted all the values. It just happens to have empty entries in between so that any Tags that have also been stored will continue to work.
But I have to admit, I don't really have a clear idea of the usage scenario for uniquestash and what is important for it to work.

I will change to store versions of empty entries sometime later today.

**Comment by Stebalien** [comment]
> But I have to admit, I don't really have a clear idea of the usage scenario for uniquestash and what is important for it to work.

The guarantee is that tag will never be reused within a single `UniqueStash`. These tags can then be used in cookies, as request IDs, as job IDs, etc. The key part here is that if the associated data in the stash is removed, the tag will never end up "pointing" to some *new* data. For example, if a job is canceled/finished, old job handles (tags) will never be reused (unlike PIDs...).

**Comment by Stebalien** [comment]
> It just happens to have empty entries in between so that any Tags that have also been stored will continue to work.

Basically, the issue is that any Tags pointing to "old" data may *also* work (but may end up pointing to new data).

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
Awesome work! Thanks!

**Pull request merged**
